---
title: Harris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    gallery:
      image: 
      title: 
      blurb: 
      text_colour: 
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    gallery:
      image: 
      title: 
      blurb: 
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: https://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
